name: antq-fe CI/CD
on:
  push:
    branches:
      - main
jobs:
  main_job:
    name: antq-fe Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ref: main
      - name: Scp file to aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ECS_IP }}
          port: ${{ secrets.ECS_SSH_PORT }}
          username: ${{ secrets.ECS_USER }}
          password: ${{ secrets.ECS_PASSWORD }}
          source: "dist"
          target: "/docker-data/nginx"
      - name: Distribution and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_IP }}
          port: ${{ secrets.ECS_SSH_PORT }}
          username: ${{ secrets.ECS_USER }}
          password: ${{ secrets.ECS_PASSWORD }}
          script: |
            cd /docker-data/nginx
            rm -rf html
            mv dist html
            docker restart nginx
            echo "Distribution END"